name: Fuzz Parser

permissions:
  contents: read

on:
  push:
    branches: [master]
    paths:
      - typescript/src/scanner.c
      - tsx/src/scanner.c
      - common/scanner.h
  pull_request:
    paths:
      - typescript/src/scanner.c
      - tsx/src/scanner.c
      - common/scanner.h

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        language: [typescript, tsx]
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Fuzz ${{matrix.language}} parser
        uses: tree-sitter/fuzz-action@6a1dcff00aefd038ba418bd63732a9add4901266 # v4
        with:
          directory: ${{matrix.language}}
          tree-sitter-version: v0.24.4
